# Generated by Django 4.1.7 on 2023-03-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="firstname",
            new_name="first_name",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="lastname",
            new_name="last_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="updated_date",
        ),
        migrations.AddField(
            model_name="user",
            name="modified_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.PositiveSmallIntegerField(
                blank=True, choices=[(1, "Restaurant"), (2, "Customer")], null=True
            ),
        ),
    ]
